### ISSUE TITLE
Unable to create connections with latest version 21.0.1.1186

### ISSUE THREAD

**Issue by jorgebslu** [idea-statica/iom-examples#93]
**Unable to export ModelBIM to latest version 21.0.1.1186**

With (former) version 21.0.0.3277 I was able to export the [attached model](https://github.com/idea-statica/iom-examples/files/6671680/d1f7e359-01c4-41e0-8817-1e2a7a0274ac-ModelBim-IOM.zip) to `CodeCheckManager`, but with the latest version (21.0.1.1186), I get the following error "Can not create connection. Invalid internal forces.":

![image](https://user-images.githubusercontent.com/66376954/122434694-9e6eb980-cf97-11eb-87fb-a65d619d8d95.png)

**With version 21.0.0.3277 all connections were imported without any problem (including internal forces)**

![image](https://user-images.githubusercontent.com/66376954/122435293-2ce33b00-cf98-11eb-94cd-601bdf32f876.png)

Please, I beg you some help to know what is going wrong with the latest version 21.0.1.1186
Regards
Jorge

**Comment by mpospisil** [comment]
Hi Jorge,
you are right - it is a bug in this patch. We have already  fixed it. The fix will be in the next patch (the next week)
Martin

**Comment by vojtech-chalupa** [comment]
The patch has 21.0.2.1036 has now been released, your issue should be fixed. Can you confirm? Thank you.

**Comment by jorgebslu** [comment]
Hi @vojtech-chalupa 
I have tested this issue with latest patch 21.0.2.1036 and I still have the issue. The message _"Can not create connection. Invalid internal forces."_ is still shown.
The issue also happens when testing with [FEAppExample_1](https://github.com/idea-statica/ideastatica-public/tree/main/src/Examples/CCM/FEAppExample_1).

![image](https://user-images.githubusercontent.com/66376954/123788198-07312c80-d8dc-11eb-949e-fb80c577ad71.png)

[Here](https://github.com/idea-statica/iom-examples/files/6732934/08-ModelBim.zip) you have a small example for testing.
I was trying to use that example to test #89 but I cannot check that the cutting of stiffening members is actually fixed by the mentioned patch.
Am I doing anything wrong 🤔  ?

Best regards
Jorge

![image](https://user-images.githubusercontent.com/66376954/123789148-241a2f80-d8dd-11eb-9b02-6f107a4c260b.png)

**Comment by vojtech-chalupa** [comment]
Hello, I will check the issue with your example. Further logs might be needed, as I can't replicate it fully on my side. I will keep you posted.

I have extracted the OpenModel from your example and managed to use ConnectionHiddenCalculation to verify #89, seems to be working fine now.

[08-ModelBim-IOM.zip](https://github.com/idea-statica/iom-examples/files/6733103/08-ModelBim-IOM.zip)

**Comment by jorgebslu** [comment]
Hello, maybe you could try first with FEAppExample_1.
FYI, previous example is just one of the connections of the larger original model.

Here you also have my CCM log file:
[IdeaStatiCaCodeCheckManager.zip](https://github.com/idea-statica/iom-examples/files/6733158/IdeaStatiCaCodeCheckManager.zip)

**Comment by vojtech-chalupa** [comment]
I've tried with FEAppExample_1, already, but could not replicate your error. mpospisil will have a look at the logs (mine and yours).

**Comment by mpospisil** [comment]
Hi Jorge,

you are righ. We added a check of the imported internal forces in a previous version. But this check is too strict in case of importing from a CAD application - there are no internal forces in your IOM file.

I have removed this check. We will send you a path tomorrow.

**Comment by jorgebslu** [comment]
Hi @mpospisil and @vojtech-chalupa:
Thank you very much for taking care of this issue !!!
Best regards
Jorge

**Comment by mpospisil** [comment]
there is the link to patch.

https://jurajsabatkaideastatica-my.sharepoint.com/:u:/g/personal/martin_pospisil_ideastatica_com/EcRs2fU5HdtFtV29C7NjPBYBQoY6Feo1SfU9XW8akng8Dg?e=3BNmGH

I can import your IOM correctly
